// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgNpc.proto

#ifndef PROTOBUF_MsgNpc_2eproto__INCLUDED
#define PROTOBUF_MsgNpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "MsgType.pb.h"
#include "MsgMove.pb.h"
#include "MsgBuff.pb.h"
// @@protoc_insertion_point(includes)

namespace MsgPB {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MsgNpc_2eproto();
void protobuf_AssignDesc_MsgNpc_2eproto();
void protobuf_ShutdownFile_MsgNpc_2eproto();

class MsgNpcRentC2S;
class MsgNpcRentResultS2C;
class MsgNpcGiftC2S;
class MsgNpcGiftResultS2C;
class MsgNpcFeaturesC2S;
class MsgNpcFeaturesResultS2C;
class MsgNpcCreateG2C;
class MsgNpcDestroyG2C;
class MsgNpcAppearance;

enum MsgNpcRentResultS2C_RESULT {
  MsgNpcRentResultS2C_RESULT_FAILURE = -1,
  MsgNpcRentResultS2C_RESULT_SUCCESS = 0
};
bool MsgNpcRentResultS2C_RESULT_IsValid(int value);
const MsgNpcRentResultS2C_RESULT MsgNpcRentResultS2C_RESULT_RESULT_MIN = MsgNpcRentResultS2C_RESULT_FAILURE;
const MsgNpcRentResultS2C_RESULT MsgNpcRentResultS2C_RESULT_RESULT_MAX = MsgNpcRentResultS2C_RESULT_SUCCESS;
const int MsgNpcRentResultS2C_RESULT_RESULT_ARRAYSIZE = MsgNpcRentResultS2C_RESULT_RESULT_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgNpcRentResultS2C_RESULT_descriptor();
inline const ::std::string& MsgNpcRentResultS2C_RESULT_Name(MsgNpcRentResultS2C_RESULT value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgNpcRentResultS2C_RESULT_descriptor(), value);
}
inline bool MsgNpcRentResultS2C_RESULT_Parse(
    const ::std::string& name, MsgNpcRentResultS2C_RESULT* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgNpcRentResultS2C_RESULT>(
    MsgNpcRentResultS2C_RESULT_descriptor(), name, value);
}
enum MsgNpcGiftResultS2C_RESULT {
  MsgNpcGiftResultS2C_RESULT_FAILURE = -1,
  MsgNpcGiftResultS2C_RESULT_SUCCESS = 0
};
bool MsgNpcGiftResultS2C_RESULT_IsValid(int value);
const MsgNpcGiftResultS2C_RESULT MsgNpcGiftResultS2C_RESULT_RESULT_MIN = MsgNpcGiftResultS2C_RESULT_FAILURE;
const MsgNpcGiftResultS2C_RESULT MsgNpcGiftResultS2C_RESULT_RESULT_MAX = MsgNpcGiftResultS2C_RESULT_SUCCESS;
const int MsgNpcGiftResultS2C_RESULT_RESULT_ARRAYSIZE = MsgNpcGiftResultS2C_RESULT_RESULT_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgNpcGiftResultS2C_RESULT_descriptor();
inline const ::std::string& MsgNpcGiftResultS2C_RESULT_Name(MsgNpcGiftResultS2C_RESULT value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgNpcGiftResultS2C_RESULT_descriptor(), value);
}
inline bool MsgNpcGiftResultS2C_RESULT_Parse(
    const ::std::string& name, MsgNpcGiftResultS2C_RESULT* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgNpcGiftResultS2C_RESULT>(
    MsgNpcGiftResultS2C_RESULT_descriptor(), name, value);
}
enum MsgNpcFeaturesResultS2C_RESULT {
  MsgNpcFeaturesResultS2C_RESULT_FAILURE = -1,
  MsgNpcFeaturesResultS2C_RESULT_SUCCESS = 0
};
bool MsgNpcFeaturesResultS2C_RESULT_IsValid(int value);
const MsgNpcFeaturesResultS2C_RESULT MsgNpcFeaturesResultS2C_RESULT_RESULT_MIN = MsgNpcFeaturesResultS2C_RESULT_FAILURE;
const MsgNpcFeaturesResultS2C_RESULT MsgNpcFeaturesResultS2C_RESULT_RESULT_MAX = MsgNpcFeaturesResultS2C_RESULT_SUCCESS;
const int MsgNpcFeaturesResultS2C_RESULT_RESULT_ARRAYSIZE = MsgNpcFeaturesResultS2C_RESULT_RESULT_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgNpcFeaturesResultS2C_RESULT_descriptor();
inline const ::std::string& MsgNpcFeaturesResultS2C_RESULT_Name(MsgNpcFeaturesResultS2C_RESULT value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgNpcFeaturesResultS2C_RESULT_descriptor(), value);
}
inline bool MsgNpcFeaturesResultS2C_RESULT_Parse(
    const ::std::string& name, MsgNpcFeaturesResultS2C_RESULT* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgNpcFeaturesResultS2C_RESULT>(
    MsgNpcFeaturesResultS2C_RESULT_descriptor(), name, value);
}
// ===================================================================

class MsgNpcRentC2S : public ::google::protobuf::Message {
 public:
  MsgNpcRentC2S();
  virtual ~MsgNpcRentC2S();

  MsgNpcRentC2S(const MsgNpcRentC2S& from);

  inline MsgNpcRentC2S& operator=(const MsgNpcRentC2S& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgNpcRentC2S& default_instance();

  void Swap(MsgNpcRentC2S* other);

  // implements Message ----------------------------------------------

  MsgNpcRentC2S* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgNpcRentC2S& from);
  void MergeFrom(const MsgNpcRentC2S& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_RENT_C2S];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional int32 npcDefID = 2;
  inline bool has_npcdefid() const;
  inline void clear_npcdefid();
  static const int kNpcDefIDFieldNumber = 2;
  inline ::google::protobuf::int32 npcdefid() const;
  inline void set_npcdefid(::google::protobuf::int32 value);

  // optional int32 mapObjectID = 3;
  inline bool has_mapobjectid() const;
  inline void clear_mapobjectid();
  static const int kMapObjectIDFieldNumber = 3;
  inline ::google::protobuf::int32 mapobjectid() const;
  inline void set_mapobjectid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MsgPB.MsgNpcRentC2S)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_npcdefid();
  inline void clear_has_npcdefid();
  inline void set_has_mapobjectid();
  inline void clear_has_mapobjectid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int msgtype_;
  ::google::protobuf::int32 npcdefid_;
  ::google::protobuf::int32 mapobjectid_;
  friend void  protobuf_AddDesc_MsgNpc_2eproto();
  friend void protobuf_AssignDesc_MsgNpc_2eproto();
  friend void protobuf_ShutdownFile_MsgNpc_2eproto();

  void InitAsDefaultInstance();
  static MsgNpcRentC2S* default_instance_;
};
// -------------------------------------------------------------------

class MsgNpcRentResultS2C : public ::google::protobuf::Message {
 public:
  MsgNpcRentResultS2C();
  virtual ~MsgNpcRentResultS2C();

  MsgNpcRentResultS2C(const MsgNpcRentResultS2C& from);

  inline MsgNpcRentResultS2C& operator=(const MsgNpcRentResultS2C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgNpcRentResultS2C& default_instance();

  void Swap(MsgNpcRentResultS2C* other);

  // implements Message ----------------------------------------------

  MsgNpcRentResultS2C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgNpcRentResultS2C& from);
  void MergeFrom(const MsgNpcRentResultS2C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef MsgNpcRentResultS2C_RESULT RESULT;
  static const RESULT FAILURE = MsgNpcRentResultS2C_RESULT_FAILURE;
  static const RESULT SUCCESS = MsgNpcRentResultS2C_RESULT_SUCCESS;
  static inline bool RESULT_IsValid(int value) {
    return MsgNpcRentResultS2C_RESULT_IsValid(value);
  }
  static const RESULT RESULT_MIN =
    MsgNpcRentResultS2C_RESULT_RESULT_MIN;
  static const RESULT RESULT_MAX =
    MsgNpcRentResultS2C_RESULT_RESULT_MAX;
  static const int RESULT_ARRAYSIZE =
    MsgNpcRentResultS2C_RESULT_RESULT_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RESULT_descriptor() {
    return MsgNpcRentResultS2C_RESULT_descriptor();
  }
  static inline const ::std::string& RESULT_Name(RESULT value) {
    return MsgNpcRentResultS2C_RESULT_Name(value);
  }
  static inline bool RESULT_Parse(const ::std::string& name,
      RESULT* value) {
    return MsgNpcRentResultS2C_RESULT_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_RENT_RESULT_S2C];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional .MsgPB.MsgNpcRentResultS2C.RESULT result = 2;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 2;
  inline ::MsgPB::MsgNpcRentResultS2C_RESULT result() const;
  inline void set_result(::MsgPB::MsgNpcRentResultS2C_RESULT value);

  // optional int32 coin = 3;
  inline bool has_coin() const;
  inline void clear_coin();
  static const int kCoinFieldNumber = 3;
  inline ::google::protobuf::int32 coin() const;
  inline void set_coin(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MsgPB.MsgNpcRentResultS2C)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_coin();
  inline void clear_has_coin();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int msgtype_;
  int result_;
  ::google::protobuf::int32 coin_;
  friend void  protobuf_AddDesc_MsgNpc_2eproto();
  friend void protobuf_AssignDesc_MsgNpc_2eproto();
  friend void protobuf_ShutdownFile_MsgNpc_2eproto();

  void InitAsDefaultInstance();
  static MsgNpcRentResultS2C* default_instance_;
};
// -------------------------------------------------------------------

class MsgNpcGiftC2S : public ::google::protobuf::Message {
 public:
  MsgNpcGiftC2S();
  virtual ~MsgNpcGiftC2S();

  MsgNpcGiftC2S(const MsgNpcGiftC2S& from);

  inline MsgNpcGiftC2S& operator=(const MsgNpcGiftC2S& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgNpcGiftC2S& default_instance();

  void Swap(MsgNpcGiftC2S* other);

  // implements Message ----------------------------------------------

  MsgNpcGiftC2S* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgNpcGiftC2S& from);
  void MergeFrom(const MsgNpcGiftC2S& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_GIFT_C2S];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional int32 npcDefID = 2;
  inline bool has_npcdefid() const;
  inline void clear_npcdefid();
  static const int kNpcDefIDFieldNumber = 2;
  inline ::google::protobuf::int32 npcdefid() const;
  inline void set_npcdefid(::google::protobuf::int32 value);

  // optional int32 mapObjectID = 3;
  inline bool has_mapobjectid() const;
  inline void clear_mapobjectid();
  static const int kMapObjectIDFieldNumber = 3;
  inline ::google::protobuf::int32 mapobjectid() const;
  inline void set_mapobjectid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MsgPB.MsgNpcGiftC2S)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_npcdefid();
  inline void clear_has_npcdefid();
  inline void set_has_mapobjectid();
  inline void clear_has_mapobjectid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int msgtype_;
  ::google::protobuf::int32 npcdefid_;
  ::google::protobuf::int32 mapobjectid_;
  friend void  protobuf_AddDesc_MsgNpc_2eproto();
  friend void protobuf_AssignDesc_MsgNpc_2eproto();
  friend void protobuf_ShutdownFile_MsgNpc_2eproto();

  void InitAsDefaultInstance();
  static MsgNpcGiftC2S* default_instance_;
};
// -------------------------------------------------------------------

class MsgNpcGiftResultS2C : public ::google::protobuf::Message {
 public:
  MsgNpcGiftResultS2C();
  virtual ~MsgNpcGiftResultS2C();

  MsgNpcGiftResultS2C(const MsgNpcGiftResultS2C& from);

  inline MsgNpcGiftResultS2C& operator=(const MsgNpcGiftResultS2C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgNpcGiftResultS2C& default_instance();

  void Swap(MsgNpcGiftResultS2C* other);

  // implements Message ----------------------------------------------

  MsgNpcGiftResultS2C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgNpcGiftResultS2C& from);
  void MergeFrom(const MsgNpcGiftResultS2C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef MsgNpcGiftResultS2C_RESULT RESULT;
  static const RESULT FAILURE = MsgNpcGiftResultS2C_RESULT_FAILURE;
  static const RESULT SUCCESS = MsgNpcGiftResultS2C_RESULT_SUCCESS;
  static inline bool RESULT_IsValid(int value) {
    return MsgNpcGiftResultS2C_RESULT_IsValid(value);
  }
  static const RESULT RESULT_MIN =
    MsgNpcGiftResultS2C_RESULT_RESULT_MIN;
  static const RESULT RESULT_MAX =
    MsgNpcGiftResultS2C_RESULT_RESULT_MAX;
  static const int RESULT_ARRAYSIZE =
    MsgNpcGiftResultS2C_RESULT_RESULT_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RESULT_descriptor() {
    return MsgNpcGiftResultS2C_RESULT_descriptor();
  }
  static inline const ::std::string& RESULT_Name(RESULT value) {
    return MsgNpcGiftResultS2C_RESULT_Name(value);
  }
  static inline bool RESULT_Parse(const ::std::string& name,
      RESULT* value) {
    return MsgNpcGiftResultS2C_RESULT_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_GIFT_RESULT_S2C];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional .MsgPB.MsgNpcGiftResultS2C.RESULT result = 2;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 2;
  inline ::MsgPB::MsgNpcGiftResultS2C_RESULT result() const;
  inline void set_result(::MsgPB::MsgNpcGiftResultS2C_RESULT value);

  // optional int32 itemID = 3;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemIDFieldNumber = 3;
  inline ::google::protobuf::int32 itemid() const;
  inline void set_itemid(::google::protobuf::int32 value);

  // optional int32 itemCount = 4;
  inline bool has_itemcount() const;
  inline void clear_itemcount();
  static const int kItemCountFieldNumber = 4;
  inline ::google::protobuf::int32 itemcount() const;
  inline void set_itemcount(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MsgPB.MsgNpcGiftResultS2C)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_itemid();
  inline void clear_has_itemid();
  inline void set_has_itemcount();
  inline void clear_has_itemcount();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int msgtype_;
  int result_;
  ::google::protobuf::int32 itemid_;
  ::google::protobuf::int32 itemcount_;
  friend void  protobuf_AddDesc_MsgNpc_2eproto();
  friend void protobuf_AssignDesc_MsgNpc_2eproto();
  friend void protobuf_ShutdownFile_MsgNpc_2eproto();

  void InitAsDefaultInstance();
  static MsgNpcGiftResultS2C* default_instance_;
};
// -------------------------------------------------------------------

class MsgNpcFeaturesC2S : public ::google::protobuf::Message {
 public:
  MsgNpcFeaturesC2S();
  virtual ~MsgNpcFeaturesC2S();

  MsgNpcFeaturesC2S(const MsgNpcFeaturesC2S& from);

  inline MsgNpcFeaturesC2S& operator=(const MsgNpcFeaturesC2S& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgNpcFeaturesC2S& default_instance();

  void Swap(MsgNpcFeaturesC2S* other);

  // implements Message ----------------------------------------------

  MsgNpcFeaturesC2S* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgNpcFeaturesC2S& from);
  void MergeFrom(const MsgNpcFeaturesC2S& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_FEATURES_C2S];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional int32 npcDefID = 2;
  inline bool has_npcdefid() const;
  inline void clear_npcdefid();
  static const int kNpcDefIDFieldNumber = 2;
  inline ::google::protobuf::int32 npcdefid() const;
  inline void set_npcdefid(::google::protobuf::int32 value);

  // optional int32 mapObjectID = 3;
  inline bool has_mapobjectid() const;
  inline void clear_mapobjectid();
  static const int kMapObjectIDFieldNumber = 3;
  inline ::google::protobuf::int32 mapobjectid() const;
  inline void set_mapobjectid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MsgPB.MsgNpcFeaturesC2S)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_npcdefid();
  inline void clear_has_npcdefid();
  inline void set_has_mapobjectid();
  inline void clear_has_mapobjectid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int msgtype_;
  ::google::protobuf::int32 npcdefid_;
  ::google::protobuf::int32 mapobjectid_;
  friend void  protobuf_AddDesc_MsgNpc_2eproto();
  friend void protobuf_AssignDesc_MsgNpc_2eproto();
  friend void protobuf_ShutdownFile_MsgNpc_2eproto();

  void InitAsDefaultInstance();
  static MsgNpcFeaturesC2S* default_instance_;
};
// -------------------------------------------------------------------

class MsgNpcFeaturesResultS2C : public ::google::protobuf::Message {
 public:
  MsgNpcFeaturesResultS2C();
  virtual ~MsgNpcFeaturesResultS2C();

  MsgNpcFeaturesResultS2C(const MsgNpcFeaturesResultS2C& from);

  inline MsgNpcFeaturesResultS2C& operator=(const MsgNpcFeaturesResultS2C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgNpcFeaturesResultS2C& default_instance();

  void Swap(MsgNpcFeaturesResultS2C* other);

  // implements Message ----------------------------------------------

  MsgNpcFeaturesResultS2C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgNpcFeaturesResultS2C& from);
  void MergeFrom(const MsgNpcFeaturesResultS2C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef MsgNpcFeaturesResultS2C_RESULT RESULT;
  static const RESULT FAILURE = MsgNpcFeaturesResultS2C_RESULT_FAILURE;
  static const RESULT SUCCESS = MsgNpcFeaturesResultS2C_RESULT_SUCCESS;
  static inline bool RESULT_IsValid(int value) {
    return MsgNpcFeaturesResultS2C_RESULT_IsValid(value);
  }
  static const RESULT RESULT_MIN =
    MsgNpcFeaturesResultS2C_RESULT_RESULT_MIN;
  static const RESULT RESULT_MAX =
    MsgNpcFeaturesResultS2C_RESULT_RESULT_MAX;
  static const int RESULT_ARRAYSIZE =
    MsgNpcFeaturesResultS2C_RESULT_RESULT_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RESULT_descriptor() {
    return MsgNpcFeaturesResultS2C_RESULT_descriptor();
  }
  static inline const ::std::string& RESULT_Name(RESULT value) {
    return MsgNpcFeaturesResultS2C_RESULT_Name(value);
  }
  static inline bool RESULT_Parse(const ::std::string& name,
      RESULT* value) {
    return MsgNpcFeaturesResultS2C_RESULT_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_FEATURES_RESULT_S2C];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional .MsgPB.MsgNpcFeaturesResultS2C.RESULT result = 2;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 2;
  inline ::MsgPB::MsgNpcFeaturesResultS2C_RESULT result() const;
  inline void set_result(::MsgPB::MsgNpcFeaturesResultS2C_RESULT value);

  // @@protoc_insertion_point(class_scope:MsgPB.MsgNpcFeaturesResultS2C)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int msgtype_;
  int result_;
  friend void  protobuf_AddDesc_MsgNpc_2eproto();
  friend void protobuf_AssignDesc_MsgNpc_2eproto();
  friend void protobuf_ShutdownFile_MsgNpc_2eproto();

  void InitAsDefaultInstance();
  static MsgNpcFeaturesResultS2C* default_instance_;
};
// -------------------------------------------------------------------

class MsgNpcCreateG2C : public ::google::protobuf::Message {
 public:
  MsgNpcCreateG2C();
  virtual ~MsgNpcCreateG2C();

  MsgNpcCreateG2C(const MsgNpcCreateG2C& from);

  inline MsgNpcCreateG2C& operator=(const MsgNpcCreateG2C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgNpcCreateG2C& default_instance();

  void Swap(MsgNpcCreateG2C* other);

  // implements Message ----------------------------------------------

  MsgNpcCreateG2C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgNpcCreateG2C& from);
  void MergeFrom(const MsgNpcCreateG2C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_CREATE_G2C];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional int64 npcInsID = 2;
  inline bool has_npcinsid() const;
  inline void clear_npcinsid();
  static const int kNpcInsIDFieldNumber = 2;
  inline ::google::protobuf::int64 npcinsid() const;
  inline void set_npcinsid(::google::protobuf::int64 value);

  // optional int32 npcDefID = 3;
  inline bool has_npcdefid() const;
  inline void clear_npcdefid();
  static const int kNpcDefIDFieldNumber = 3;
  inline ::google::protobuf::int32 npcdefid() const;
  inline void set_npcdefid(::google::protobuf::int32 value);

  // optional int32 mapObjectID = 4;
  inline bool has_mapobjectid() const;
  inline void clear_mapobjectid();
  static const int kMapObjectIDFieldNumber = 4;
  inline ::google::protobuf::int32 mapobjectid() const;
  inline void set_mapobjectid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MsgPB.MsgNpcCreateG2C)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_npcinsid();
  inline void clear_has_npcinsid();
  inline void set_has_npcdefid();
  inline void clear_has_npcdefid();
  inline void set_has_mapobjectid();
  inline void clear_has_mapobjectid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 npcinsid_;
  int msgtype_;
  ::google::protobuf::int32 npcdefid_;
  ::google::protobuf::int32 mapobjectid_;
  friend void  protobuf_AddDesc_MsgNpc_2eproto();
  friend void protobuf_AssignDesc_MsgNpc_2eproto();
  friend void protobuf_ShutdownFile_MsgNpc_2eproto();

  void InitAsDefaultInstance();
  static MsgNpcCreateG2C* default_instance_;
};
// -------------------------------------------------------------------

class MsgNpcDestroyG2C : public ::google::protobuf::Message {
 public:
  MsgNpcDestroyG2C();
  virtual ~MsgNpcDestroyG2C();

  MsgNpcDestroyG2C(const MsgNpcDestroyG2C& from);

  inline MsgNpcDestroyG2C& operator=(const MsgNpcDestroyG2C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgNpcDestroyG2C& default_instance();

  void Swap(MsgNpcDestroyG2C* other);

  // implements Message ----------------------------------------------

  MsgNpcDestroyG2C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgNpcDestroyG2C& from);
  void MergeFrom(const MsgNpcDestroyG2C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_DESTROY_G2C];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional int64 npcInsID = 2;
  inline bool has_npcinsid() const;
  inline void clear_npcinsid();
  static const int kNpcInsIDFieldNumber = 2;
  inline ::google::protobuf::int64 npcinsid() const;
  inline void set_npcinsid(::google::protobuf::int64 value);

  // optional int32 mapObjectID = 3;
  inline bool has_mapobjectid() const;
  inline void clear_mapobjectid();
  static const int kMapObjectIDFieldNumber = 3;
  inline ::google::protobuf::int32 mapobjectid() const;
  inline void set_mapobjectid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MsgPB.MsgNpcDestroyG2C)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_npcinsid();
  inline void clear_has_npcinsid();
  inline void set_has_mapobjectid();
  inline void clear_has_mapobjectid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 npcinsid_;
  int msgtype_;
  ::google::protobuf::int32 mapobjectid_;
  friend void  protobuf_AddDesc_MsgNpc_2eproto();
  friend void protobuf_AssignDesc_MsgNpc_2eproto();
  friend void protobuf_ShutdownFile_MsgNpc_2eproto();

  void InitAsDefaultInstance();
  static MsgNpcDestroyG2C* default_instance_;
};
// -------------------------------------------------------------------

class MsgNpcAppearance : public ::google::protobuf::Message {
 public:
  MsgNpcAppearance();
  virtual ~MsgNpcAppearance();

  MsgNpcAppearance(const MsgNpcAppearance& from);

  inline MsgNpcAppearance& operator=(const MsgNpcAppearance& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgNpcAppearance& default_instance();

  void Swap(MsgNpcAppearance* other);

  // implements Message ----------------------------------------------

  MsgNpcAppearance* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgNpcAppearance& from);
  void MergeFrom(const MsgNpcAppearance& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_APPEARACE];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional int64 npcInsID = 2;
  inline bool has_npcinsid() const;
  inline void clear_npcinsid();
  static const int kNpcInsIDFieldNumber = 2;
  inline ::google::protobuf::int64 npcinsid() const;
  inline void set_npcinsid(::google::protobuf::int64 value);

  // optional int32 npcDefId = 3;
  inline bool has_npcdefid() const;
  inline void clear_npcdefid();
  static const int kNpcDefIdFieldNumber = 3;
  inline ::google::protobuf::int32 npcdefid() const;
  inline void set_npcdefid(::google::protobuf::int32 value);

  // optional int32 mapObjectId = 4;
  inline bool has_mapobjectid() const;
  inline void clear_mapobjectid();
  static const int kMapObjectIdFieldNumber = 4;
  inline ::google::protobuf::int32 mapobjectid() const;
  inline void set_mapobjectid(::google::protobuf::int32 value);

  // optional .MsgPB.MsgMovePath movePath = 7;
  inline bool has_movepath() const;
  inline void clear_movepath();
  static const int kMovePathFieldNumber = 7;
  inline const ::MsgPB::MsgMovePath& movepath() const;
  inline ::MsgPB::MsgMovePath* mutable_movepath();
  inline ::MsgPB::MsgMovePath* release_movepath();
  inline void set_allocated_movepath(::MsgPB::MsgMovePath* movepath);

  // repeated .MsgPB.ServerBuffInfo buff_infos = 8;
  inline int buff_infos_size() const;
  inline void clear_buff_infos();
  static const int kBuffInfosFieldNumber = 8;
  inline const ::MsgPB::ServerBuffInfo& buff_infos(int index) const;
  inline ::MsgPB::ServerBuffInfo* mutable_buff_infos(int index);
  inline ::MsgPB::ServerBuffInfo* add_buff_infos();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgPB::ServerBuffInfo >&
      buff_infos() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgPB::ServerBuffInfo >*
      mutable_buff_infos();

  // @@protoc_insertion_point(class_scope:MsgPB.MsgNpcAppearance)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_npcinsid();
  inline void clear_has_npcinsid();
  inline void set_has_npcdefid();
  inline void clear_has_npcdefid();
  inline void set_has_mapobjectid();
  inline void clear_has_mapobjectid();
  inline void set_has_movepath();
  inline void clear_has_movepath();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 npcinsid_;
  int msgtype_;
  ::google::protobuf::int32 npcdefid_;
  ::MsgPB::MsgMovePath* movepath_;
  ::google::protobuf::RepeatedPtrField< ::MsgPB::ServerBuffInfo > buff_infos_;
  ::google::protobuf::int32 mapobjectid_;
  friend void  protobuf_AddDesc_MsgNpc_2eproto();
  friend void protobuf_AssignDesc_MsgNpc_2eproto();
  friend void protobuf_ShutdownFile_MsgNpc_2eproto();

  void InitAsDefaultInstance();
  static MsgNpcAppearance* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgNpcRentC2S

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_RENT_C2S];
inline bool MsgNpcRentC2S::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgNpcRentC2S::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgNpcRentC2S::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgNpcRentC2S::clear_msgtype() {
  msgtype_ = 1550;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgNpcRentC2S::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcRentC2S.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgNpcRentC2S::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcRentC2S.msgType)
}

// optional int32 npcDefID = 2;
inline bool MsgNpcRentC2S::has_npcdefid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgNpcRentC2S::set_has_npcdefid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgNpcRentC2S::clear_has_npcdefid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgNpcRentC2S::clear_npcdefid() {
  npcdefid_ = 0;
  clear_has_npcdefid();
}
inline ::google::protobuf::int32 MsgNpcRentC2S::npcdefid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcRentC2S.npcDefID)
  return npcdefid_;
}
inline void MsgNpcRentC2S::set_npcdefid(::google::protobuf::int32 value) {
  set_has_npcdefid();
  npcdefid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcRentC2S.npcDefID)
}

// optional int32 mapObjectID = 3;
inline bool MsgNpcRentC2S::has_mapobjectid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgNpcRentC2S::set_has_mapobjectid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgNpcRentC2S::clear_has_mapobjectid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgNpcRentC2S::clear_mapobjectid() {
  mapobjectid_ = 0;
  clear_has_mapobjectid();
}
inline ::google::protobuf::int32 MsgNpcRentC2S::mapobjectid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcRentC2S.mapObjectID)
  return mapobjectid_;
}
inline void MsgNpcRentC2S::set_mapobjectid(::google::protobuf::int32 value) {
  set_has_mapobjectid();
  mapobjectid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcRentC2S.mapObjectID)
}

// -------------------------------------------------------------------

// MsgNpcRentResultS2C

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_RENT_RESULT_S2C];
inline bool MsgNpcRentResultS2C::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgNpcRentResultS2C::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgNpcRentResultS2C::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgNpcRentResultS2C::clear_msgtype() {
  msgtype_ = 1551;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgNpcRentResultS2C::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcRentResultS2C.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgNpcRentResultS2C::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcRentResultS2C.msgType)
}

// optional .MsgPB.MsgNpcRentResultS2C.RESULT result = 2;
inline bool MsgNpcRentResultS2C::has_result() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgNpcRentResultS2C::set_has_result() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgNpcRentResultS2C::clear_has_result() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgNpcRentResultS2C::clear_result() {
  result_ = -1;
  clear_has_result();
}
inline ::MsgPB::MsgNpcRentResultS2C_RESULT MsgNpcRentResultS2C::result() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcRentResultS2C.result)
  return static_cast< ::MsgPB::MsgNpcRentResultS2C_RESULT >(result_);
}
inline void MsgNpcRentResultS2C::set_result(::MsgPB::MsgNpcRentResultS2C_RESULT value) {
  assert(::MsgPB::MsgNpcRentResultS2C_RESULT_IsValid(value));
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcRentResultS2C.result)
}

// optional int32 coin = 3;
inline bool MsgNpcRentResultS2C::has_coin() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgNpcRentResultS2C::set_has_coin() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgNpcRentResultS2C::clear_has_coin() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgNpcRentResultS2C::clear_coin() {
  coin_ = 0;
  clear_has_coin();
}
inline ::google::protobuf::int32 MsgNpcRentResultS2C::coin() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcRentResultS2C.coin)
  return coin_;
}
inline void MsgNpcRentResultS2C::set_coin(::google::protobuf::int32 value) {
  set_has_coin();
  coin_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcRentResultS2C.coin)
}

// -------------------------------------------------------------------

// MsgNpcGiftC2S

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_GIFT_C2S];
inline bool MsgNpcGiftC2S::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgNpcGiftC2S::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgNpcGiftC2S::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgNpcGiftC2S::clear_msgtype() {
  msgtype_ = 1552;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgNpcGiftC2S::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcGiftC2S.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgNpcGiftC2S::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcGiftC2S.msgType)
}

// optional int32 npcDefID = 2;
inline bool MsgNpcGiftC2S::has_npcdefid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgNpcGiftC2S::set_has_npcdefid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgNpcGiftC2S::clear_has_npcdefid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgNpcGiftC2S::clear_npcdefid() {
  npcdefid_ = 0;
  clear_has_npcdefid();
}
inline ::google::protobuf::int32 MsgNpcGiftC2S::npcdefid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcGiftC2S.npcDefID)
  return npcdefid_;
}
inline void MsgNpcGiftC2S::set_npcdefid(::google::protobuf::int32 value) {
  set_has_npcdefid();
  npcdefid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcGiftC2S.npcDefID)
}

// optional int32 mapObjectID = 3;
inline bool MsgNpcGiftC2S::has_mapobjectid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgNpcGiftC2S::set_has_mapobjectid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgNpcGiftC2S::clear_has_mapobjectid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgNpcGiftC2S::clear_mapobjectid() {
  mapobjectid_ = 0;
  clear_has_mapobjectid();
}
inline ::google::protobuf::int32 MsgNpcGiftC2S::mapobjectid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcGiftC2S.mapObjectID)
  return mapobjectid_;
}
inline void MsgNpcGiftC2S::set_mapobjectid(::google::protobuf::int32 value) {
  set_has_mapobjectid();
  mapobjectid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcGiftC2S.mapObjectID)
}

// -------------------------------------------------------------------

// MsgNpcGiftResultS2C

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_GIFT_RESULT_S2C];
inline bool MsgNpcGiftResultS2C::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgNpcGiftResultS2C::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgNpcGiftResultS2C::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgNpcGiftResultS2C::clear_msgtype() {
  msgtype_ = 1553;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgNpcGiftResultS2C::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcGiftResultS2C.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgNpcGiftResultS2C::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcGiftResultS2C.msgType)
}

// optional .MsgPB.MsgNpcGiftResultS2C.RESULT result = 2;
inline bool MsgNpcGiftResultS2C::has_result() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgNpcGiftResultS2C::set_has_result() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgNpcGiftResultS2C::clear_has_result() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgNpcGiftResultS2C::clear_result() {
  result_ = -1;
  clear_has_result();
}
inline ::MsgPB::MsgNpcGiftResultS2C_RESULT MsgNpcGiftResultS2C::result() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcGiftResultS2C.result)
  return static_cast< ::MsgPB::MsgNpcGiftResultS2C_RESULT >(result_);
}
inline void MsgNpcGiftResultS2C::set_result(::MsgPB::MsgNpcGiftResultS2C_RESULT value) {
  assert(::MsgPB::MsgNpcGiftResultS2C_RESULT_IsValid(value));
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcGiftResultS2C.result)
}

// optional int32 itemID = 3;
inline bool MsgNpcGiftResultS2C::has_itemid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgNpcGiftResultS2C::set_has_itemid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgNpcGiftResultS2C::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgNpcGiftResultS2C::clear_itemid() {
  itemid_ = 0;
  clear_has_itemid();
}
inline ::google::protobuf::int32 MsgNpcGiftResultS2C::itemid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcGiftResultS2C.itemID)
  return itemid_;
}
inline void MsgNpcGiftResultS2C::set_itemid(::google::protobuf::int32 value) {
  set_has_itemid();
  itemid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcGiftResultS2C.itemID)
}

// optional int32 itemCount = 4;
inline bool MsgNpcGiftResultS2C::has_itemcount() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgNpcGiftResultS2C::set_has_itemcount() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgNpcGiftResultS2C::clear_has_itemcount() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgNpcGiftResultS2C::clear_itemcount() {
  itemcount_ = 0;
  clear_has_itemcount();
}
inline ::google::protobuf::int32 MsgNpcGiftResultS2C::itemcount() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcGiftResultS2C.itemCount)
  return itemcount_;
}
inline void MsgNpcGiftResultS2C::set_itemcount(::google::protobuf::int32 value) {
  set_has_itemcount();
  itemcount_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcGiftResultS2C.itemCount)
}

// -------------------------------------------------------------------

// MsgNpcFeaturesC2S

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_FEATURES_C2S];
inline bool MsgNpcFeaturesC2S::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgNpcFeaturesC2S::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgNpcFeaturesC2S::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgNpcFeaturesC2S::clear_msgtype() {
  msgtype_ = 1554;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgNpcFeaturesC2S::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcFeaturesC2S.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgNpcFeaturesC2S::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcFeaturesC2S.msgType)
}

// optional int32 npcDefID = 2;
inline bool MsgNpcFeaturesC2S::has_npcdefid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgNpcFeaturesC2S::set_has_npcdefid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgNpcFeaturesC2S::clear_has_npcdefid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgNpcFeaturesC2S::clear_npcdefid() {
  npcdefid_ = 0;
  clear_has_npcdefid();
}
inline ::google::protobuf::int32 MsgNpcFeaturesC2S::npcdefid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcFeaturesC2S.npcDefID)
  return npcdefid_;
}
inline void MsgNpcFeaturesC2S::set_npcdefid(::google::protobuf::int32 value) {
  set_has_npcdefid();
  npcdefid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcFeaturesC2S.npcDefID)
}

// optional int32 mapObjectID = 3;
inline bool MsgNpcFeaturesC2S::has_mapobjectid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgNpcFeaturesC2S::set_has_mapobjectid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgNpcFeaturesC2S::clear_has_mapobjectid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgNpcFeaturesC2S::clear_mapobjectid() {
  mapobjectid_ = 0;
  clear_has_mapobjectid();
}
inline ::google::protobuf::int32 MsgNpcFeaturesC2S::mapobjectid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcFeaturesC2S.mapObjectID)
  return mapobjectid_;
}
inline void MsgNpcFeaturesC2S::set_mapobjectid(::google::protobuf::int32 value) {
  set_has_mapobjectid();
  mapobjectid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcFeaturesC2S.mapObjectID)
}

// -------------------------------------------------------------------

// MsgNpcFeaturesResultS2C

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_FEATURES_RESULT_S2C];
inline bool MsgNpcFeaturesResultS2C::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgNpcFeaturesResultS2C::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgNpcFeaturesResultS2C::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgNpcFeaturesResultS2C::clear_msgtype() {
  msgtype_ = 1555;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgNpcFeaturesResultS2C::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcFeaturesResultS2C.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgNpcFeaturesResultS2C::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcFeaturesResultS2C.msgType)
}

// optional .MsgPB.MsgNpcFeaturesResultS2C.RESULT result = 2;
inline bool MsgNpcFeaturesResultS2C::has_result() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgNpcFeaturesResultS2C::set_has_result() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgNpcFeaturesResultS2C::clear_has_result() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgNpcFeaturesResultS2C::clear_result() {
  result_ = -1;
  clear_has_result();
}
inline ::MsgPB::MsgNpcFeaturesResultS2C_RESULT MsgNpcFeaturesResultS2C::result() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcFeaturesResultS2C.result)
  return static_cast< ::MsgPB::MsgNpcFeaturesResultS2C_RESULT >(result_);
}
inline void MsgNpcFeaturesResultS2C::set_result(::MsgPB::MsgNpcFeaturesResultS2C_RESULT value) {
  assert(::MsgPB::MsgNpcFeaturesResultS2C_RESULT_IsValid(value));
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcFeaturesResultS2C.result)
}

// -------------------------------------------------------------------

// MsgNpcCreateG2C

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_CREATE_G2C];
inline bool MsgNpcCreateG2C::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgNpcCreateG2C::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgNpcCreateG2C::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgNpcCreateG2C::clear_msgtype() {
  msgtype_ = 1566;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgNpcCreateG2C::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcCreateG2C.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgNpcCreateG2C::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcCreateG2C.msgType)
}

// optional int64 npcInsID = 2;
inline bool MsgNpcCreateG2C::has_npcinsid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgNpcCreateG2C::set_has_npcinsid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgNpcCreateG2C::clear_has_npcinsid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgNpcCreateG2C::clear_npcinsid() {
  npcinsid_ = GOOGLE_LONGLONG(0);
  clear_has_npcinsid();
}
inline ::google::protobuf::int64 MsgNpcCreateG2C::npcinsid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcCreateG2C.npcInsID)
  return npcinsid_;
}
inline void MsgNpcCreateG2C::set_npcinsid(::google::protobuf::int64 value) {
  set_has_npcinsid();
  npcinsid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcCreateG2C.npcInsID)
}

// optional int32 npcDefID = 3;
inline bool MsgNpcCreateG2C::has_npcdefid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgNpcCreateG2C::set_has_npcdefid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgNpcCreateG2C::clear_has_npcdefid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgNpcCreateG2C::clear_npcdefid() {
  npcdefid_ = 0;
  clear_has_npcdefid();
}
inline ::google::protobuf::int32 MsgNpcCreateG2C::npcdefid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcCreateG2C.npcDefID)
  return npcdefid_;
}
inline void MsgNpcCreateG2C::set_npcdefid(::google::protobuf::int32 value) {
  set_has_npcdefid();
  npcdefid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcCreateG2C.npcDefID)
}

// optional int32 mapObjectID = 4;
inline bool MsgNpcCreateG2C::has_mapobjectid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgNpcCreateG2C::set_has_mapobjectid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgNpcCreateG2C::clear_has_mapobjectid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgNpcCreateG2C::clear_mapobjectid() {
  mapobjectid_ = 0;
  clear_has_mapobjectid();
}
inline ::google::protobuf::int32 MsgNpcCreateG2C::mapobjectid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcCreateG2C.mapObjectID)
  return mapobjectid_;
}
inline void MsgNpcCreateG2C::set_mapobjectid(::google::protobuf::int32 value) {
  set_has_mapobjectid();
  mapobjectid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcCreateG2C.mapObjectID)
}

// -------------------------------------------------------------------

// MsgNpcDestroyG2C

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_DESTROY_G2C];
inline bool MsgNpcDestroyG2C::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgNpcDestroyG2C::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgNpcDestroyG2C::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgNpcDestroyG2C::clear_msgtype() {
  msgtype_ = 1567;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgNpcDestroyG2C::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcDestroyG2C.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgNpcDestroyG2C::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcDestroyG2C.msgType)
}

// optional int64 npcInsID = 2;
inline bool MsgNpcDestroyG2C::has_npcinsid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgNpcDestroyG2C::set_has_npcinsid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgNpcDestroyG2C::clear_has_npcinsid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgNpcDestroyG2C::clear_npcinsid() {
  npcinsid_ = GOOGLE_LONGLONG(0);
  clear_has_npcinsid();
}
inline ::google::protobuf::int64 MsgNpcDestroyG2C::npcinsid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcDestroyG2C.npcInsID)
  return npcinsid_;
}
inline void MsgNpcDestroyG2C::set_npcinsid(::google::protobuf::int64 value) {
  set_has_npcinsid();
  npcinsid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcDestroyG2C.npcInsID)
}

// optional int32 mapObjectID = 3;
inline bool MsgNpcDestroyG2C::has_mapobjectid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgNpcDestroyG2C::set_has_mapobjectid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgNpcDestroyG2C::clear_has_mapobjectid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgNpcDestroyG2C::clear_mapobjectid() {
  mapobjectid_ = 0;
  clear_has_mapobjectid();
}
inline ::google::protobuf::int32 MsgNpcDestroyG2C::mapobjectid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcDestroyG2C.mapObjectID)
  return mapobjectid_;
}
inline void MsgNpcDestroyG2C::set_mapobjectid(::google::protobuf::int32 value) {
  set_has_mapobjectid();
  mapobjectid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcDestroyG2C.mapObjectID)
}

// -------------------------------------------------------------------

// MsgNpcAppearance

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_NPC_APPEARACE];
inline bool MsgNpcAppearance::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgNpcAppearance::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgNpcAppearance::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgNpcAppearance::clear_msgtype() {
  msgtype_ = 1568;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgNpcAppearance::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcAppearance.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgNpcAppearance::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcAppearance.msgType)
}

// optional int64 npcInsID = 2;
inline bool MsgNpcAppearance::has_npcinsid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgNpcAppearance::set_has_npcinsid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgNpcAppearance::clear_has_npcinsid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgNpcAppearance::clear_npcinsid() {
  npcinsid_ = GOOGLE_LONGLONG(0);
  clear_has_npcinsid();
}
inline ::google::protobuf::int64 MsgNpcAppearance::npcinsid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcAppearance.npcInsID)
  return npcinsid_;
}
inline void MsgNpcAppearance::set_npcinsid(::google::protobuf::int64 value) {
  set_has_npcinsid();
  npcinsid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcAppearance.npcInsID)
}

// optional int32 npcDefId = 3;
inline bool MsgNpcAppearance::has_npcdefid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgNpcAppearance::set_has_npcdefid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgNpcAppearance::clear_has_npcdefid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgNpcAppearance::clear_npcdefid() {
  npcdefid_ = 0;
  clear_has_npcdefid();
}
inline ::google::protobuf::int32 MsgNpcAppearance::npcdefid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcAppearance.npcDefId)
  return npcdefid_;
}
inline void MsgNpcAppearance::set_npcdefid(::google::protobuf::int32 value) {
  set_has_npcdefid();
  npcdefid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcAppearance.npcDefId)
}

// optional int32 mapObjectId = 4;
inline bool MsgNpcAppearance::has_mapobjectid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgNpcAppearance::set_has_mapobjectid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgNpcAppearance::clear_has_mapobjectid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgNpcAppearance::clear_mapobjectid() {
  mapobjectid_ = 0;
  clear_has_mapobjectid();
}
inline ::google::protobuf::int32 MsgNpcAppearance::mapobjectid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcAppearance.mapObjectId)
  return mapobjectid_;
}
inline void MsgNpcAppearance::set_mapobjectid(::google::protobuf::int32 value) {
  set_has_mapobjectid();
  mapobjectid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgNpcAppearance.mapObjectId)
}

// optional .MsgPB.MsgMovePath movePath = 7;
inline bool MsgNpcAppearance::has_movepath() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgNpcAppearance::set_has_movepath() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgNpcAppearance::clear_has_movepath() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgNpcAppearance::clear_movepath() {
  if (movepath_ != NULL) movepath_->::MsgPB::MsgMovePath::Clear();
  clear_has_movepath();
}
inline const ::MsgPB::MsgMovePath& MsgNpcAppearance::movepath() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcAppearance.movePath)
  return movepath_ != NULL ? *movepath_ : *default_instance_->movepath_;
}
inline ::MsgPB::MsgMovePath* MsgNpcAppearance::mutable_movepath() {
  set_has_movepath();
  if (movepath_ == NULL) movepath_ = new ::MsgPB::MsgMovePath;
  // @@protoc_insertion_point(field_mutable:MsgPB.MsgNpcAppearance.movePath)
  return movepath_;
}
inline ::MsgPB::MsgMovePath* MsgNpcAppearance::release_movepath() {
  clear_has_movepath();
  ::MsgPB::MsgMovePath* temp = movepath_;
  movepath_ = NULL;
  return temp;
}
inline void MsgNpcAppearance::set_allocated_movepath(::MsgPB::MsgMovePath* movepath) {
  delete movepath_;
  movepath_ = movepath;
  if (movepath) {
    set_has_movepath();
  } else {
    clear_has_movepath();
  }
  // @@protoc_insertion_point(field_set_allocated:MsgPB.MsgNpcAppearance.movePath)
}

// repeated .MsgPB.ServerBuffInfo buff_infos = 8;
inline int MsgNpcAppearance::buff_infos_size() const {
  return buff_infos_.size();
}
inline void MsgNpcAppearance::clear_buff_infos() {
  buff_infos_.Clear();
}
inline const ::MsgPB::ServerBuffInfo& MsgNpcAppearance::buff_infos(int index) const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgNpcAppearance.buff_infos)
  return buff_infos_.Get(index);
}
inline ::MsgPB::ServerBuffInfo* MsgNpcAppearance::mutable_buff_infos(int index) {
  // @@protoc_insertion_point(field_mutable:MsgPB.MsgNpcAppearance.buff_infos)
  return buff_infos_.Mutable(index);
}
inline ::MsgPB::ServerBuffInfo* MsgNpcAppearance::add_buff_infos() {
  // @@protoc_insertion_point(field_add:MsgPB.MsgNpcAppearance.buff_infos)
  return buff_infos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgPB::ServerBuffInfo >&
MsgNpcAppearance::buff_infos() const {
  // @@protoc_insertion_point(field_list:MsgPB.MsgNpcAppearance.buff_infos)
  return buff_infos_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgPB::ServerBuffInfo >*
MsgNpcAppearance::mutable_buff_infos() {
  // @@protoc_insertion_point(field_mutable_list:MsgPB.MsgNpcAppearance.buff_infos)
  return &buff_infos_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MsgPB

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MsgPB::MsgNpcRentResultS2C_RESULT> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MsgPB::MsgNpcRentResultS2C_RESULT>() {
  return ::MsgPB::MsgNpcRentResultS2C_RESULT_descriptor();
}
template <> struct is_proto_enum< ::MsgPB::MsgNpcGiftResultS2C_RESULT> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MsgPB::MsgNpcGiftResultS2C_RESULT>() {
  return ::MsgPB::MsgNpcGiftResultS2C_RESULT_descriptor();
}
template <> struct is_proto_enum< ::MsgPB::MsgNpcFeaturesResultS2C_RESULT> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MsgPB::MsgNpcFeaturesResultS2C_RESULT>() {
  return ::MsgPB::MsgNpcFeaturesResultS2C_RESULT_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgNpc_2eproto__INCLUDED
