// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgSyncToUserServer.proto

#ifndef PROTOBUF_MsgSyncToUserServer_2eproto__INCLUDED
#define PROTOBUF_MsgSyncToUserServer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "MsgType.pb.h"
// @@protoc_insertion_point(includes)

namespace MsgPB {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MsgSyncToUserServer_2eproto();
void protobuf_AssignDesc_MsgSyncToUserServer_2eproto();
void protobuf_ShutdownFile_MsgSyncToUserServer_2eproto();

class MsgUpdateUserStatus;

// ===================================================================

class MsgUpdateUserStatus : public ::google::protobuf::Message {
 public:
  MsgUpdateUserStatus();
  virtual ~MsgUpdateUserStatus();

  MsgUpdateUserStatus(const MsgUpdateUserStatus& from);

  inline MsgUpdateUserStatus& operator=(const MsgUpdateUserStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgUpdateUserStatus& default_instance();

  void Swap(MsgUpdateUserStatus* other);

  // implements Message ----------------------------------------------

  MsgUpdateUserStatus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgUpdateUserStatus& from);
  void MergeFrom(const MsgUpdateUserStatus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_UPDATE_USER_STATUS];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional int64 iggid = 2;
  inline bool has_iggid() const;
  inline void clear_iggid();
  static const int kIggidFieldNumber = 2;
  inline ::google::protobuf::int64 iggid() const;
  inline void set_iggid(::google::protobuf::int64 value);

  // optional int32 status = 3;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 3;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MsgPB.MsgUpdateUserStatus)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_iggid();
  inline void clear_has_iggid();
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 iggid_;
  int msgtype_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_AddDesc_MsgSyncToUserServer_2eproto();
  friend void protobuf_AssignDesc_MsgSyncToUserServer_2eproto();
  friend void protobuf_ShutdownFile_MsgSyncToUserServer_2eproto();

  void InitAsDefaultInstance();
  static MsgUpdateUserStatus* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgUpdateUserStatus

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_UPDATE_USER_STATUS];
inline bool MsgUpdateUserStatus::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgUpdateUserStatus::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgUpdateUserStatus::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgUpdateUserStatus::clear_msgtype() {
  msgtype_ = 1022;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgUpdateUserStatus::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgUpdateUserStatus.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgUpdateUserStatus::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgUpdateUserStatus.msgType)
}

// optional int64 iggid = 2;
inline bool MsgUpdateUserStatus::has_iggid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgUpdateUserStatus::set_has_iggid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgUpdateUserStatus::clear_has_iggid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgUpdateUserStatus::clear_iggid() {
  iggid_ = GOOGLE_LONGLONG(0);
  clear_has_iggid();
}
inline ::google::protobuf::int64 MsgUpdateUserStatus::iggid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgUpdateUserStatus.iggid)
  return iggid_;
}
inline void MsgUpdateUserStatus::set_iggid(::google::protobuf::int64 value) {
  set_has_iggid();
  iggid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgUpdateUserStatus.iggid)
}

// optional int32 status = 3;
inline bool MsgUpdateUserStatus::has_status() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgUpdateUserStatus::set_has_status() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgUpdateUserStatus::clear_has_status() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgUpdateUserStatus::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 MsgUpdateUserStatus::status() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgUpdateUserStatus.status)
  return status_;
}
inline void MsgUpdateUserStatus::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgUpdateUserStatus.status)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MsgPB

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgSyncToUserServer_2eproto__INCLUDED
