// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgSyncToUserServer.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MsgSyncToUserServer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MsgPB {

namespace {

const ::google::protobuf::Descriptor* MsgUpdateUserStatus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgUpdateUserStatus_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MsgSyncToUserServer_2eproto() {
  protobuf_AddDesc_MsgSyncToUserServer_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MsgSyncToUserServer.proto");
  GOOGLE_CHECK(file != NULL);
  MsgUpdateUserStatus_descriptor_ = file->message_type(0);
  static const int MsgUpdateUserStatus_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgUpdateUserStatus, msgtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgUpdateUserStatus, iggid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgUpdateUserStatus, status_),
  };
  MsgUpdateUserStatus_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgUpdateUserStatus_descriptor_,
      MsgUpdateUserStatus::default_instance_,
      MsgUpdateUserStatus_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgUpdateUserStatus, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgUpdateUserStatus, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgUpdateUserStatus));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MsgSyncToUserServer_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgUpdateUserStatus_descriptor_, &MsgUpdateUserStatus::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MsgSyncToUserServer_2eproto() {
  delete MsgUpdateUserStatus::default_instance_;
  delete MsgUpdateUserStatus_reflection_;
}

void protobuf_AddDesc_MsgSyncToUserServer_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::MsgPB::protobuf_AddDesc_MsgType_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\031MsgSyncToUserServer.proto\022\005MsgPB\032\rMsgT"
    "ype.proto\"o\n\023MsgUpdateUserStatus\0229\n\007msgT"
    "ype\030\001 \001(\0162\017.MsgPB.EMsgType:\027_MSG_UPDATE_"
    "USER_STATUS\022\r\n\005iggid\030\002 \001(\003\022\016\n\006status\030\003 \001"
    "(\005", 162);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MsgSyncToUserServer.proto", &protobuf_RegisterTypes);
  MsgUpdateUserStatus::default_instance_ = new MsgUpdateUserStatus();
  MsgUpdateUserStatus::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MsgSyncToUserServer_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MsgSyncToUserServer_2eproto {
  StaticDescriptorInitializer_MsgSyncToUserServer_2eproto() {
    protobuf_AddDesc_MsgSyncToUserServer_2eproto();
  }
} static_descriptor_initializer_MsgSyncToUserServer_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MsgUpdateUserStatus::kMsgTypeFieldNumber;
const int MsgUpdateUserStatus::kIggidFieldNumber;
const int MsgUpdateUserStatus::kStatusFieldNumber;
#endif  // !_MSC_VER

MsgUpdateUserStatus::MsgUpdateUserStatus()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MsgPB.MsgUpdateUserStatus)
}

void MsgUpdateUserStatus::InitAsDefaultInstance() {
}

MsgUpdateUserStatus::MsgUpdateUserStatus(const MsgUpdateUserStatus& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MsgPB.MsgUpdateUserStatus)
}

void MsgUpdateUserStatus::SharedCtor() {
  _cached_size_ = 0;
  msgtype_ = 1022;
  iggid_ = GOOGLE_LONGLONG(0);
  status_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgUpdateUserStatus::~MsgUpdateUserStatus() {
  // @@protoc_insertion_point(destructor:MsgPB.MsgUpdateUserStatus)
  SharedDtor();
}

void MsgUpdateUserStatus::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgUpdateUserStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgUpdateUserStatus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgUpdateUserStatus_descriptor_;
}

const MsgUpdateUserStatus& MsgUpdateUserStatus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MsgSyncToUserServer_2eproto();
  return *default_instance_;
}

MsgUpdateUserStatus* MsgUpdateUserStatus::default_instance_ = NULL;

MsgUpdateUserStatus* MsgUpdateUserStatus::New() const {
  return new MsgUpdateUserStatus;
}

void MsgUpdateUserStatus::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    msgtype_ = 1022;
    iggid_ = GOOGLE_LONGLONG(0);
    status_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgUpdateUserStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MsgPB.MsgUpdateUserStatus)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_UPDATE_USER_STATUS];
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::MsgPB::EMsgType_IsValid(value)) {
            set_msgtype(static_cast< ::MsgPB::EMsgType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_iggid;
        break;
      }

      // optional int64 iggid = 2;
      case 2: {
        if (tag == 16) {
         parse_iggid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &iggid_)));
          set_has_iggid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_status;
        break;
      }

      // optional int32 status = 3;
      case 3: {
        if (tag == 24) {
         parse_status:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &status_)));
          set_has_status();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MsgPB.MsgUpdateUserStatus)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MsgPB.MsgUpdateUserStatus)
  return false;
#undef DO_
}

void MsgUpdateUserStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MsgPB.MsgUpdateUserStatus)
  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_UPDATE_USER_STATUS];
  if (has_msgtype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msgtype(), output);
  }

  // optional int64 iggid = 2;
  if (has_iggid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->iggid(), output);
  }

  // optional int32 status = 3;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->status(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MsgPB.MsgUpdateUserStatus)
}

::google::protobuf::uint8* MsgUpdateUserStatus::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgPB.MsgUpdateUserStatus)
  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_UPDATE_USER_STATUS];
  if (has_msgtype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->msgtype(), target);
  }

  // optional int64 iggid = 2;
  if (has_iggid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->iggid(), target);
  }

  // optional int32 status = 3;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->status(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MsgPB.MsgUpdateUserStatus)
  return target;
}

int MsgUpdateUserStatus::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_UPDATE_USER_STATUS];
    if (has_msgtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->msgtype());
    }

    // optional int64 iggid = 2;
    if (has_iggid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->iggid());
    }

    // optional int32 status = 3;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->status());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgUpdateUserStatus::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgUpdateUserStatus* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgUpdateUserStatus*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgUpdateUserStatus::MergeFrom(const MsgUpdateUserStatus& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msgtype()) {
      set_msgtype(from.msgtype());
    }
    if (from.has_iggid()) {
      set_iggid(from.iggid());
    }
    if (from.has_status()) {
      set_status(from.status());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgUpdateUserStatus::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgUpdateUserStatus::CopyFrom(const MsgUpdateUserStatus& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgUpdateUserStatus::IsInitialized() const {

  return true;
}

void MsgUpdateUserStatus::Swap(MsgUpdateUserStatus* other) {
  if (other != this) {
    std::swap(msgtype_, other->msgtype_);
    std::swap(iggid_, other->iggid_);
    std::swap(status_, other->status_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgUpdateUserStatus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgUpdateUserStatus_descriptor_;
  metadata.reflection = MsgUpdateUserStatus_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MsgPB

// @@protoc_insertion_point(global_scope)
