// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgTroops.proto

#ifndef PROTOBUF_MsgTroops_2eproto__INCLUDED
#define PROTOBUF_MsgTroops_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "MsgType.pb.h"
// @@protoc_insertion_point(includes)

namespace MsgPB {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MsgTroops_2eproto();
void protobuf_AssignDesc_MsgTroops_2eproto();
void protobuf_ShutdownFile_MsgTroops_2eproto();

class TroopsInfo;
class MsgTroopsC2S;
class MsgTroopsS2C;

enum MsgTroopsS2C_RESULT {
  MsgTroopsS2C_RESULT_FAILURE = -1,
  MsgTroopsS2C_RESULT_SUCCESS = 0
};
bool MsgTroopsS2C_RESULT_IsValid(int value);
const MsgTroopsS2C_RESULT MsgTroopsS2C_RESULT_RESULT_MIN = MsgTroopsS2C_RESULT_FAILURE;
const MsgTroopsS2C_RESULT MsgTroopsS2C_RESULT_RESULT_MAX = MsgTroopsS2C_RESULT_SUCCESS;
const int MsgTroopsS2C_RESULT_RESULT_ARRAYSIZE = MsgTroopsS2C_RESULT_RESULT_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgTroopsS2C_RESULT_descriptor();
inline const ::std::string& MsgTroopsS2C_RESULT_Name(MsgTroopsS2C_RESULT value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgTroopsS2C_RESULT_descriptor(), value);
}
inline bool MsgTroopsS2C_RESULT_Parse(
    const ::std::string& name, MsgTroopsS2C_RESULT* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgTroopsS2C_RESULT>(
    MsgTroopsS2C_RESULT_descriptor(), name, value);
}
// ===================================================================

class TroopsInfo : public ::google::protobuf::Message {
 public:
  TroopsInfo();
  virtual ~TroopsInfo();

  TroopsInfo(const TroopsInfo& from);

  inline TroopsInfo& operator=(const TroopsInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TroopsInfo& default_instance();

  void Swap(TroopsInfo* other);

  // implements Message ----------------------------------------------

  TroopsInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TroopsInfo& from);
  void MergeFrom(const TroopsInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 pos = 1;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 1;
  inline ::google::protobuf::int32 pos() const;
  inline void set_pos(::google::protobuf::int32 value);

  // optional int64 uuid = 2;
  inline bool has_uuid() const;
  inline void clear_uuid();
  static const int kUuidFieldNumber = 2;
  inline ::google::protobuf::int64 uuid() const;
  inline void set_uuid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MsgPB.TroopsInfo)
 private:
  inline void set_has_pos();
  inline void clear_has_pos();
  inline void set_has_uuid();
  inline void clear_has_uuid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 uuid_;
  ::google::protobuf::int32 pos_;
  friend void  protobuf_AddDesc_MsgTroops_2eproto();
  friend void protobuf_AssignDesc_MsgTroops_2eproto();
  friend void protobuf_ShutdownFile_MsgTroops_2eproto();

  void InitAsDefaultInstance();
  static TroopsInfo* default_instance_;
};
// -------------------------------------------------------------------

class MsgTroopsC2S : public ::google::protobuf::Message {
 public:
  MsgTroopsC2S();
  virtual ~MsgTroopsC2S();

  MsgTroopsC2S(const MsgTroopsC2S& from);

  inline MsgTroopsC2S& operator=(const MsgTroopsC2S& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgTroopsC2S& default_instance();

  void Swap(MsgTroopsC2S* other);

  // implements Message ----------------------------------------------

  MsgTroopsC2S* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgTroopsC2S& from);
  void MergeFrom(const MsgTroopsC2S& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_TROOPS_PROTECTOR_UP_C2S];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional int64 iggid = 2;
  inline bool has_iggid() const;
  inline void clear_iggid();
  static const int kIggidFieldNumber = 2;
  inline ::google::protobuf::int64 iggid() const;
  inline void set_iggid(::google::protobuf::int64 value);

  // optional int32 troopId = 3;
  inline bool has_troopid() const;
  inline void clear_troopid();
  static const int kTroopIdFieldNumber = 3;
  inline ::google::protobuf::int32 troopid() const;
  inline void set_troopid(::google::protobuf::int32 value);

  // repeated .MsgPB.TroopsInfo data = 4;
  inline int data_size() const;
  inline void clear_data();
  static const int kDataFieldNumber = 4;
  inline const ::MsgPB::TroopsInfo& data(int index) const;
  inline ::MsgPB::TroopsInfo* mutable_data(int index);
  inline ::MsgPB::TroopsInfo* add_data();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgPB::TroopsInfo >&
      data() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgPB::TroopsInfo >*
      mutable_data();

  // @@protoc_insertion_point(class_scope:MsgPB.MsgTroopsC2S)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_iggid();
  inline void clear_has_iggid();
  inline void set_has_troopid();
  inline void clear_has_troopid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 iggid_;
  int msgtype_;
  ::google::protobuf::int32 troopid_;
  ::google::protobuf::RepeatedPtrField< ::MsgPB::TroopsInfo > data_;
  friend void  protobuf_AddDesc_MsgTroops_2eproto();
  friend void protobuf_AssignDesc_MsgTroops_2eproto();
  friend void protobuf_ShutdownFile_MsgTroops_2eproto();

  void InitAsDefaultInstance();
  static MsgTroopsC2S* default_instance_;
};
// -------------------------------------------------------------------

class MsgTroopsS2C : public ::google::protobuf::Message {
 public:
  MsgTroopsS2C();
  virtual ~MsgTroopsS2C();

  MsgTroopsS2C(const MsgTroopsS2C& from);

  inline MsgTroopsS2C& operator=(const MsgTroopsS2C& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgTroopsS2C& default_instance();

  void Swap(MsgTroopsS2C* other);

  // implements Message ----------------------------------------------

  MsgTroopsS2C* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgTroopsS2C& from);
  void MergeFrom(const MsgTroopsS2C& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef MsgTroopsS2C_RESULT RESULT;
  static const RESULT FAILURE = MsgTroopsS2C_RESULT_FAILURE;
  static const RESULT SUCCESS = MsgTroopsS2C_RESULT_SUCCESS;
  static inline bool RESULT_IsValid(int value) {
    return MsgTroopsS2C_RESULT_IsValid(value);
  }
  static const RESULT RESULT_MIN =
    MsgTroopsS2C_RESULT_RESULT_MIN;
  static const RESULT RESULT_MAX =
    MsgTroopsS2C_RESULT_RESULT_MAX;
  static const int RESULT_ARRAYSIZE =
    MsgTroopsS2C_RESULT_RESULT_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RESULT_descriptor() {
    return MsgTroopsS2C_RESULT_descriptor();
  }
  static inline const ::std::string& RESULT_Name(RESULT value) {
    return MsgTroopsS2C_RESULT_Name(value);
  }
  static inline bool RESULT_Parse(const ::std::string& name,
      RESULT* value) {
    return MsgTroopsS2C_RESULT_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .MsgPB.EMsgType msgType = 1 [default = _MSG_TROOPS_PROTECTOR_UP_S2C];
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline ::MsgPB::EMsgType msgtype() const;
  inline void set_msgtype(::MsgPB::EMsgType value);

  // optional .MsgPB.MsgTroopsS2C.RESULT result = 2;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 2;
  inline ::MsgPB::MsgTroopsS2C_RESULT result() const;
  inline void set_result(::MsgPB::MsgTroopsS2C_RESULT value);

  // @@protoc_insertion_point(class_scope:MsgPB.MsgTroopsS2C)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int msgtype_;
  int result_;
  friend void  protobuf_AddDesc_MsgTroops_2eproto();
  friend void protobuf_AssignDesc_MsgTroops_2eproto();
  friend void protobuf_ShutdownFile_MsgTroops_2eproto();

  void InitAsDefaultInstance();
  static MsgTroopsS2C* default_instance_;
};
// ===================================================================


// ===================================================================

// TroopsInfo

// optional int32 pos = 1;
inline bool TroopsInfo::has_pos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TroopsInfo::set_has_pos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TroopsInfo::clear_has_pos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TroopsInfo::clear_pos() {
  pos_ = 0;
  clear_has_pos();
}
inline ::google::protobuf::int32 TroopsInfo::pos() const {
  // @@protoc_insertion_point(field_get:MsgPB.TroopsInfo.pos)
  return pos_;
}
inline void TroopsInfo::set_pos(::google::protobuf::int32 value) {
  set_has_pos();
  pos_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.TroopsInfo.pos)
}

// optional int64 uuid = 2;
inline bool TroopsInfo::has_uuid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TroopsInfo::set_has_uuid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TroopsInfo::clear_has_uuid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TroopsInfo::clear_uuid() {
  uuid_ = GOOGLE_LONGLONG(0);
  clear_has_uuid();
}
inline ::google::protobuf::int64 TroopsInfo::uuid() const {
  // @@protoc_insertion_point(field_get:MsgPB.TroopsInfo.uuid)
  return uuid_;
}
inline void TroopsInfo::set_uuid(::google::protobuf::int64 value) {
  set_has_uuid();
  uuid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.TroopsInfo.uuid)
}

// -------------------------------------------------------------------

// MsgTroopsC2S

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_TROOPS_PROTECTOR_UP_C2S];
inline bool MsgTroopsC2S::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgTroopsC2S::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgTroopsC2S::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgTroopsC2S::clear_msgtype() {
  msgtype_ = 8200;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgTroopsC2S::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgTroopsC2S.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgTroopsC2S::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgTroopsC2S.msgType)
}

// optional int64 iggid = 2;
inline bool MsgTroopsC2S::has_iggid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgTroopsC2S::set_has_iggid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgTroopsC2S::clear_has_iggid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgTroopsC2S::clear_iggid() {
  iggid_ = GOOGLE_LONGLONG(0);
  clear_has_iggid();
}
inline ::google::protobuf::int64 MsgTroopsC2S::iggid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgTroopsC2S.iggid)
  return iggid_;
}
inline void MsgTroopsC2S::set_iggid(::google::protobuf::int64 value) {
  set_has_iggid();
  iggid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgTroopsC2S.iggid)
}

// optional int32 troopId = 3;
inline bool MsgTroopsC2S::has_troopid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgTroopsC2S::set_has_troopid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgTroopsC2S::clear_has_troopid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgTroopsC2S::clear_troopid() {
  troopid_ = 0;
  clear_has_troopid();
}
inline ::google::protobuf::int32 MsgTroopsC2S::troopid() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgTroopsC2S.troopId)
  return troopid_;
}
inline void MsgTroopsC2S::set_troopid(::google::protobuf::int32 value) {
  set_has_troopid();
  troopid_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgTroopsC2S.troopId)
}

// repeated .MsgPB.TroopsInfo data = 4;
inline int MsgTroopsC2S::data_size() const {
  return data_.size();
}
inline void MsgTroopsC2S::clear_data() {
  data_.Clear();
}
inline const ::MsgPB::TroopsInfo& MsgTroopsC2S::data(int index) const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgTroopsC2S.data)
  return data_.Get(index);
}
inline ::MsgPB::TroopsInfo* MsgTroopsC2S::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:MsgPB.MsgTroopsC2S.data)
  return data_.Mutable(index);
}
inline ::MsgPB::TroopsInfo* MsgTroopsC2S::add_data() {
  // @@protoc_insertion_point(field_add:MsgPB.MsgTroopsC2S.data)
  return data_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgPB::TroopsInfo >&
MsgTroopsC2S::data() const {
  // @@protoc_insertion_point(field_list:MsgPB.MsgTroopsC2S.data)
  return data_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgPB::TroopsInfo >*
MsgTroopsC2S::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:MsgPB.MsgTroopsC2S.data)
  return &data_;
}

// -------------------------------------------------------------------

// MsgTroopsS2C

// optional .MsgPB.EMsgType msgType = 1 [default = _MSG_TROOPS_PROTECTOR_UP_S2C];
inline bool MsgTroopsS2C::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgTroopsS2C::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgTroopsS2C::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgTroopsS2C::clear_msgtype() {
  msgtype_ = 8201;
  clear_has_msgtype();
}
inline ::MsgPB::EMsgType MsgTroopsS2C::msgtype() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgTroopsS2C.msgType)
  return static_cast< ::MsgPB::EMsgType >(msgtype_);
}
inline void MsgTroopsS2C::set_msgtype(::MsgPB::EMsgType value) {
  assert(::MsgPB::EMsgType_IsValid(value));
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgTroopsS2C.msgType)
}

// optional .MsgPB.MsgTroopsS2C.RESULT result = 2;
inline bool MsgTroopsS2C::has_result() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgTroopsS2C::set_has_result() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgTroopsS2C::clear_has_result() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgTroopsS2C::clear_result() {
  result_ = -1;
  clear_has_result();
}
inline ::MsgPB::MsgTroopsS2C_RESULT MsgTroopsS2C::result() const {
  // @@protoc_insertion_point(field_get:MsgPB.MsgTroopsS2C.result)
  return static_cast< ::MsgPB::MsgTroopsS2C_RESULT >(result_);
}
inline void MsgTroopsS2C::set_result(::MsgPB::MsgTroopsS2C_RESULT value) {
  assert(::MsgPB::MsgTroopsS2C_RESULT_IsValid(value));
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:MsgPB.MsgTroopsS2C.result)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MsgPB

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MsgPB::MsgTroopsS2C_RESULT> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MsgPB::MsgTroopsS2C_RESULT>() {
  return ::MsgPB::MsgTroopsS2C_RESULT_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgTroops_2eproto__INCLUDED
